### ISSUE TITLE
 aiohttp.server ERROR Error handling request

### ISSUE THREAD

**Issue by Ravijha93** [bcgov/indy-email-verification#20]
Getting the below error while creating genesis transaction for email-verifier-agent:

File "/home/indy/src/aries-cloudagent/aries_cloudagent/ledger/indy.py", line 220, in _submit
email-verifier-agent_1     |     f"Ledger rejected transaction request: {request_result['reason']}"
email-verifier-agent_1     | aries_cloudagent.ledger.error.LedgerTransactionError: Ledger rejected transaction request: client request invalid: UnauthorizedClientRequest('The action is forbidden',)

**Comment by swcurran** [comment]
Sorry for the delay in responding.  My guess this is an error related to connecting with the ledger.  How are you starting up with ledger and the controller/agent?  What platform are you on. My guess is that it's a connection problem between the agent and ledger.

**Comment by esune** [comment]
@swcurran closing this as it has become inactive. It can be reopened if necessary.
