### ISSUE TITLE
email-verifier-service_1   | ConnectionRefusedError: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by EtricKombat** [bcgov/indy-email-verification#58]
### Getting the listed error while trying to bring up the indy-email-verification service

![image](https://user-images.githubusercontent.com/33585301/93978457-a5b2bf00-fd99-11ea-9868-0a734575f0e5.png)

![image](https://user-images.githubusercontent.com/33585301/93977994-f7a71500-fd98-11ea-8bfb-ca15dcb872fe.png)

#### Terminal 1 : 

        cd indy-email-verification/
        ./start-ngrok.sh

#### Terminal 2 : 

        cd indy-email-verification/docker/
        ./manage down
        ./manage build
        ./manage start

### machine details

![image](https://user-images.githubusercontent.com/33585301/93978269-5c626f80-fd99-11ea-94b4-7ac19ff46580.png)

**Comment by EtricKombat** [comment]
Hi @swcurran , could you please take a look at this and suggest why this might be causing?

**Comment by swcurran** [comment]
First idea is that you aren't running a von-network instance (or some other Indy network running).  I suspect that you have to do that separately.

@esune -- any ideas?

**Comment by esune** [comment]
> 
> 
> First idea is that you aren't running a von-network instance (or some other Indy network running). I suspect that you have to do that separately.
> 
The project will run using BCovrin Test as ledger (see [here](https://github.com/bcgov/indy-email-verification/blob/master/docker/docker-compose.yml#L20).

@EtricKombat your log screenshot doesn't seem to show an agent is running, which would cause the controller to fail when trying to post to the `/schemas` endpoint. Can you please check your docker containers and ensure the `email-verifier-agent` service is running? If it isn't, fixing that will likely make the other services start as well without errors.

**Comment by EtricKombat** [comment]
@swcurran , @esune  . Thanks for the feedback...i had this same issue for two days. 


After few more tries it got fixed. Thanks.

**Comment by EtricKombat** [comment]
@esune , next time when this occurs will check and confirm the email-verifier-agent service is running or not...
