### ISSUE TITLE
Deploy test, prod services in OCP4

### ISSUE THREAD

**Issue by esune** [bcgov/indy-email-verification#67]
`email-verification` services should be deployed in `test`, `prod`.

- `test` services are all-new and will need to be configured from scratch.
- `prod` services should have their wallets carried over from the `devex-von-image-tools` namespace so we can decommission the old ones. @wadeking98 please proceed with deploying the agent in `read only` mode, using the wallet and secret values from OCP3. Once ready, coordinate with @WadeBarnes to add the `vonx.io` routes and certificates, and switch the DNS entry to point to the new cluster.

**Comment by wadeking98** [comment]
up and running in OCP4
