### ISSUE TITLE
Issue Running Agent/App

### ISSUE THREAD

**Issue by monar24** [bcgov/indy-email-verification#84]
Running in an Ubuntu VM (18.04/20.04 -->tried both)

Following basic steps in this demo app:
1. script to start ngrok for agent tunnel 
2. manager build and then manage up 

Getting the following error for the agent container: 

<img width="1714" alt="Screenshot 2023-03-29 at 12 47 59 PM" src="https://user-images.githubusercontent.com/106766300/228611773-3ecc27a4-15c0-4ee3-bdc1-4263407ce71d.png">

When running with aca-py agent: **ghcr.io/hyperledger/aries-cloudagent-python:py3.6-indy-1.16.0-0.8.0** 

the agent has no problem, and I can pull up the swagger api http://0.0.0.0:5000/api/doc#/

With both agents, the django app sending requests to that api does not run, see logs :
(container docker_email-verifier-service_1 is outputting the same for localhost:8080)

<img width="1722" alt="1" src="https://user-images.githubusercontent.com/106766300/228614973-4b85d4b1-1deb-426d-8c27-83b832d92e90.png">

<img width="1725" alt="2" src="https://user-images.githubusercontent.com/106766300/228615020-44960ab7-1366-43f5-9c1b-8f751dd8f71c.png">

<img width="1711" alt="3" src="https://user-images.githubusercontent.com/106766300/228615067-5e1da5a8-82bf-4d4a-b2e8-05923957964a.png">

**Comment by WadeBarnes** [comment]
Closing.  Project is being retired and archived.
